add inline validation for YYYY
Enterprise-CMCS/macpro-mdct-qmr pull request #1674
Opened 2023-03-15 21:03 UTC by britt-mo

## Summary
adds inline validation for `YYYY` format in start and end date

### Description

### Related ticket
[jira](https://qmacbis.atlassian.net/jira/software/c/projects/MDCT/boards/232?modal=detail&selectedIssue=MDCT-2245)

### How to test

Go to 2023, choose any of the measures, see that there is now inline validation after you start typing the year or start and end date.

### Important updates

### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated the documentation, if necessary

2023-03-16 13:14 UTC, tblackwe requested changes

2023-03-16 13:14 UTC, tblackwe commented on services/ui-src/src/components/DateRange/index.test.tsx
> +
req: add a positive test to verify valid dates are accepted.

2023-03-16 13:14 UTC, tblackwe commented on services/ui-src/src/components/DateRange/index.tsx
> +  /* If start date is not in correct YYYY format */
are there any controls preventing me from inputting `1776`? from a quick glance the code supports anything between `1000` and `2023 (current year)`

2023-03-17 16:34 UTC, tblackwe submitted a review, later dismissed

2023-03-17 19:08 UTC, BearHanded approved these changes

2023-03-17 19:11 UTC, merged