IU-HH Text Change 2382
Enterprise-CMCS/macpro-mdct-qmr pull request #1782
Opened 2023-04-28 12:57 UTC by benmartin-coforma

### Description
Just a small text change for this measure

### Related ticket(s)
MDCT-2382

---
### How to test
1. Log in to a state with Health Home measures (for example, `stateuser6`).
2. Select FFY 2023.
3. Navigate to this measure.
4. Fill out the first three questions, to get the performance measure text to appear.
5. Check that text.

### Important updates
n/a

---
### Author checklist

- [x] I have performed a self-review of my code
- [-] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [-] I have updated relevant documentation, if necessary

2023-04-28 18:15 UTC, ajaitasaini commented
To clarify, you were getting rid of the text "health home" here?

2023-04-28 19:59 UTC, keeysnc approved these changes

2023-05-01 16:04 UTC, ntsummers1 commented on services/ui-src/src/measures/2023/IUHH/data.ts
> +    "Rate of acute inpatient care and services (total, maternity, mental and behavioral disorders, surgery, and medicine) per 1,000 enrollee months among enrollees.",
I think we want to keep the health home here? According to the ticket a red line just indicated a change. Not sure why its marked as a change though if the change is already good.. Possible we can just close this ticket and mark it as done but we should double check with David whether he actually wanted this to stay the same or be changed to something else

2023-05-01 16:05 UTC, ntsummers1 requested changes
See above

2023-05-02 16:54 UTC, benmartin-coforma commented
@ajaitasaini @ntsummers1  You're totally right. I confirmed with David K that we don't want the text remove. I'm closing this PR and scooting the ticket across the board.

2023-05-02 16:54 UTC, closed without merging