Create new measure: CPU-AD
Enterprise-CMCS/macpro-mdct-qmr pull request #1800
Opened 2023-05-08 15:39 UTC by benmartin-coforma

### Description
CPU-AD is **Long-Term Services and Supports Comprehensive Care Plan and Update** for adults.

### Related ticket(s)
MDCT-2427

---
### How to test
This is an adult measure for 2023, and it should line up with the story description.

### Important updates
n/a

---
### Author checklist
- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary

2023-05-09 15:46 UTC, karla-vm approved these changes
LGTM!

2023-05-09 16:10 UTC, keeysnc submitted a review, later dismissed
Looks good on my end!

2023-05-09 18:20 UTC, ajaitasaini requested changes

2023-05-09 18:20 UTC, ajaitasaini commented on services/ui-src/src/measures/2023/rateLabelText.ts
> +        "categories": []
categories need an id now! would add that here

2023-05-10 14:36 UTC, ajaitasaini submitted a review, later dismissed

2023-05-10 15:28 UTC, ailZhou approved these changes

2023-05-11 20:39 UTC, ailZhou approved these changes

2023-05-11 22:16 UTC, merged