MDCT-2337: Non-Required Measurement Fix (SPIKE Output)
Enterprise-CMCS/macpro-mdct-qmr pull request #1817
Opened 2023-05-31 19:05 UTC by karla-vm

### Description

In a few instances, state users reported that the auto-completed (i.e. read-only) measures were being set to `In Progress` even though these should always be marked `Complete`. After taking a look with @BearHanded we saw that on a session time-out, the auto-completed measures are getting "saved" and thus returning to the `In Progress` state.

### Related ticket(s)

MDCT-2337

---
### How to test

- Navigate to any FY Adult Measures
- Verify that `NCIDDS-AD` is set to `Complete` by default
- Navigate away and back
- It should still be set `Complete`

### Important updates

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2023-05-31 19:07 UTC, BearHanded requested changes
I think this bug would still break a normally completed measure if the user timed out while looking at it

2023-06-09 20:04 UTC, benmartin-coforma commented on services/ui-src/src/components/MeasureWrapper/index.tsx
> +    if (!mutationRunning && !loadingData && !shouldSave) {
I think this condition is backwards? Unless I'm misunderstanding, we want `shouldSave` and not `!shouldSave`.

2023-06-15 19:16 UTC, karla-vm commented on services/ui-src/src/components/MeasureWrapper/index.tsx
> +    if (!mutationRunning && !loadingData && !shouldSave) {
That is correct, just fixed it! thanks 🏆

2023-06-15 19:46 UTC, benmartin-coforma submitted a review, later dismissed
Looks good!

2023-06-20 20:31 UTC, BearHanded approved these changes

2023-06-21 17:57 UTC, keeysnc approved these changes

2023-06-21 20:00 UTC, merged