Include readable labels for Mathematica
Enterprise-CMCS/macpro-mdct-qmr pull request #1841
Opened 2023-06-29 17:22 UTC by keeysnc

### Description

### Related ticket(s)
https://qmacbis.atlassian.net/browse/MDCT-2602
MDCT-2602

---
### How to test

### Important updates

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2023-06-30 15:55 UTC, BearHanded requested changes
Looks good just a couple quick comments. I'd also appreciate @ailZhou taking a look if she has any other thoughts or knows of any edge cases.

2023-06-30 15:55 UTC, BearHanded commented on services/ui-src/src/components/IETRate/index.tsx
> +      if (getMeasureYear() === 2023) {
I think this should probably be >= 2023 to save us a headache, and can we add a comment calling out why the year is being compared?

2023-06-30 15:55 UTC, BearHanded commented on services/ui-src/src/components/Rate/index.tsx
> +      if (getMeasureYear() === 2023) {
Same as above

2023-06-30 15:55 UTC, BearHanded commented on services/ui-src/src/components/Rate/index.tsx
> +        console.log("only on 2023", prevRate);
Remove log

2023-06-30 15:55 UTC, BearHanded commented on services/ui-src/src/components/ComplexRate/index.tsx
> +      if (getMeasureYear() === 2023) {
Same as IETRate comment

2023-07-05 12:11 UTC, BearHanded approved these changes

2023-07-05 13:36 UTC, ailZhou approved these changes
Code looks good and it updated the data correctly when tested locally!

2023-07-05 13:53 UTC, merged