APM-CH/WCCCH - Validation Error
Enterprise-CMCS/macpro-mdct-qmr pull request #1879
Opened 2023-07-13 16:09 UTC by keeysnc

### Description
For these validations, an `[object Object] ` was being displayed instead of the qualifier label name. The error was due to the parameter type being 'string' but the actual value being an 'object'. Since there is only 2 (APM-CH / WCCCH) measures that are displaying this issue I thought it would be a easier solution to ignore the type check on that specific input.

Before
<img width="730" alt="Screenshot 2023-07-13 at 12 51 48 PM" src="https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/14514294/31aa5fc3-9219-435e-806c-705ad88e66f9">

After
<img width="1263" alt="Screenshot 2023-07-13 at 12 53 01 PM" src="https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/14514294/e9f86ff2-79e7-4549-beff-adb07d34da2b">

### Related ticket(s)
https://qmacbis.atlassian.net/browse/MDCT-2683
MDCT-2683

---
### How to test

### Important updates

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2023-07-14 18:36 UTC, karla-vm approved these changes

2023-07-14 19:37 UTC, britt-mo approved these changes

2023-07-17 17:26 UTC, benmartin-coforma requested changes
This change would leave in place a bug for any future measures that may call `validateTotalNDR` with three arguments (using the default error message builder).

The root cause is an `any` on line 134 of `globalValidations/validateTotals/index.tsx`, in the declaration of `totalNDR`. If you remove that `any`, the typechecker will find the issues on lines 145 and 156: We will want `categories[0].label`, rather than just `categories[0]`. The same fix will need to be applied to the construction of `fieldLabel`, on line 166.

Note: This bug isn't _currently_ surfacing for any measures beyond APM-CH or WCC-CH, but that's by coincidence. Since all other measures using this validation do not supply a `categories` argument, those three lines fall through and use `totalNDR.label` instead.

2023-07-18 22:40 UTC, keeysnc commented
> This change would leave in place a bug for any future measures that may call `validateTotalNDR` with three arguments (using the default error message builder).
> 
> The root cause is an `any` on line 134 of `globalValidations/validateTotals/index.tsx`, in the declaration of `totalNDR`. If you remove that `any`, the typechecker will find the issues on lines 145 and 156: We will want `categories[0].label`, rather than just `categories[0]`. The same fix will need to be applied to the construction of `fieldLabel`, on line 166.
> 
> Note: This bug isn't _currently_ surfacing for any measures beyond APM-CH or WCC-CH, but that's by coincidence. Since all other measures using this validation do not supply a `categories` argument, those three lines fall through and use `totalNDR.label` instead.

@benmartin-coforma Updated. Thanks for the clarification.

2023-07-19 11:44 UTC, benmartin-coforma approved these changes
Looks great!

2023-07-19 11:46 UTC, braxex approved these changes
Didn't pull down and test but code looks reasonable. LGTM.

2023-07-19 14:45 UTC, merged