Global OMS Validation
Enterprise-CMCS/macpro-mdct-qmr pull request #1927
Opened 2023-08-09 15:45 UTC by ailZhou

### Description

Currently for OMS, when selecting a sub-category and not selecting a label, it will generate a validation error. This is correct and expected.

The issue is when you have two sub-classification selected and only one of them is filled out. This causes the system to think both sub-classification had its N/D/R filled out, so no validation error is shown. 

This branch should fix that and have a validation error for the non-filled out sub-classification.

### Related ticket(s)

MDCT-2791

---
### How to test

1) Sign into QMR, any account
2) Go to AAB-AD
3) Select the first radio button for the first 3 questions, this will open up the Performance Measures
4) Go to Performance Measure, fill out the N/D/R set, every N/D/R filled will generate an equivalent check box for the OMS
5) The OMS section should be available now
6) Select the 'Race' checkbox
7) Check any two sub classification
8) Only fill out 1 sub-classification N/D/R set
9) Validate
10) There should be a validation error for the non-filled out N/D/R set.

### Important updates

N/A

---
### Author checklist

- [x] I have performed a self-review of my code
- [ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2023-08-10 15:16 UTC, BearHanded submitted a review, later dismissed
Approved, with the one naming question

2023-08-10 15:16 UTC, BearHanded commented on services/ui-src/src/measures/2023/shared/globalValidations/omsValidator/index.ts
> +  const isClassFilled: { [key: string]: boolean } = {};
Nit, feel free to ignore: When I read `isClassFilled` here I jump to an object's Class, not a qmr classification. Would it be better names along the lines of `checkIsClassificationFilled`, even if it is a mouthful?

2023-08-10 15:30 UTC, keeysnc submitted a review, later dismissed
lgtm!

2023-08-10 16:29 UTC, britt-mo commented
These two scenarios still result in no validation errors:
![Screenshot 2023-08-10 at 10 28 22 AM](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/22454493/b16a2928-355d-403c-bc01-91b3e733e887)
![Screenshot 2023-08-10 at 10 28 47 AM](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/22454493/1626e1d8-7eb7-4e94-8dc4-fb2cb52540d4)

2023-08-10 16:30 UTC, britt-mo requested changes
Left screenshots

2023-08-15 15:32 UTC, keeysnc approved these changes
lgtm!

2023-08-15 16:34 UTC, BearHanded approved these changes

2023-08-15 16:36 UTC, closed without merging