validation text change
Enterprise-CMCS/macpro-mdct-qmr pull request #2164
Opened 2024-04-04 20:38 UTC by britt-mo

### Description
`Update the language in the validation that flags when a state selects "Other Data Source" but doesn't enter text in the box provided. Currently, the flag says "Data Source Error: You must select a data source" which may be confusing to states because a data source has already been selected. Can you please update the flag language to say "Data Source Error: Please describe the Other Data Source"? `

### Related ticket(s)

CMDCT-3480

---
### How to test

### Notes

---
### Pre-review checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary

---
### Pre-merge checklist

#### Review
- [ ] Design: This work has been reviewed and approved by design, if necessary
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

#### Security
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._

- [ ] These changes are significant enough to require an update to the SIA.
- [ ] These changes are significant enough to require a penetration test.
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2024-04-08 15:59 UTC, keeysnc submitted a review, later dismissed

2024-04-09 13:22 UTC, ailZhou requested changes
I think that message is shared between any data source that is selected, even non other data source. When I select: 

<img width="989" alt="Screenshot 2024-04-09 at 9 17 37 AM" src="https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/127151429/6018d48b-de77-4b74-b37c-adb77a6e4f16">

I get 2 error message back, one validation is run against administrative data (which makes sense for the original message) and the second for other data source (which is what the new message is for).
<img width="865" alt="Screenshot 2024-04-09 at 9 17 44 AM" src="https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/127151429/8f9e247c-795a-40bb-ba77-db89a6494f0f">

I think you might need a conditional to track what the label is and then return the correct text.

2024-04-11 14:25 UTC, keeysnc approved these changes

2024-04-11 19:38 UTC, ailZhou approved these changes
lgtm! tested in deploy link and the correct validation message is displaying for both other and non other.

2024-04-11 20:14 UTC, merged