Cmdct 3450
Enterprise-CMCS/macpro-mdct-qmr pull request #2177
Opened 2024-04-12 18:43 UTC by britt-mo

### Description
just the route for the new adult core sets

### Related ticket(s)

CMDCT-3450

---
### How to test
If you uncomment line 37 in `services/ui-src/src/Routes.tsx` and  in `AddCoreSetCards.tsx`, add a new `AddCoreSetCard` component, you should see the option appear and it will take you to the new page route.

### Notes

---
### Pre-review checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary

---
### Pre-merge checklist

#### Review
- [ ] Design: This work has been reviewed and approved by design, if necessary
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

#### Security
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._

- [ ] These changes are significant enough to require an update to the SIA.
- [ ] These changes are significant enough to require a penetration test.
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2024-04-15 15:02 UTC, ailZhou requested changes
Slight change requested, as the route currently isn't accessible.

In Routes.tsx, the `AddAdultCoreSet` lazy load should be uncommented and the const should be called similar to `AddChildCoreSet` in line 167. 
`<Route path=":state/:year/add-adult" element={<AddAdultCoreSet />} />`

Without that line, that page currently is not accessible even if you add an AddCoreSetCard.

2024-04-15 15:37 UTC, gmrabian approved these changes
route works and looks right

2024-04-15 15:40 UTC, ailZhou approved these changes
lgtm! tested locally and the page is adult core set add page is rendering!

2024-04-15 17:24 UTC, ailZhou approved these changes

2024-04-17 13:22 UTC, BearHanded approved these changes

2024-04-17 14:31 UTC, gmrabian approved these changes

2024-04-18 14:34 UTC, merged