[QMR] All Child and Adult Measures - In line warning banner (Data Source)
Enterprise-CMCS/macpro-mdct-qmr pull request #2239
Opened 2024-05-17 20:51 UTC by ajaitasaini

### Description

### Related ticket(s)

CMDCT-3628

---
### How to test

### Notes

---
### Pre-review checklist

- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
- [ ] I have performed a self-review of my code
- [ ] I have manually tested this PR in the deployed cloud environment

---
### Pre-merge checklist

#### Review
- [ ] Design: This work has been reviewed and approved by design, if necessary
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

#### Security
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._

- [ ] These changes are significant enough to require an update to the SIA.
- [ ] These changes are significant enough to require a penetration test.
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2024-05-20 16:56 UTC, ailZhou commented
The locations of where you placed the alerts looks to be correct to me and they are showing up. There's just two areas that could use a second look.
1) Based on the ticket, I think only Other Data Source is suppose to have the warning and not Administrative Data Other 
<img width="1308" alt="Screenshot 2024-05-20 at 12 45 34 PM" src="https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/127151429/b45942e8-3bd6-4e81-a140-ccf4b564776f">
2) This is showing up for all the years but I think we only want this for reporting year 2024 and onward. An example of how we handle only rendering something for a year and not the other can be seen in `OptionalMeasureStrat/index.ts`. If the text key exist in the commonQuestionsLabel.tsx for that year, it will render, if not, it will ignore it.

<img width="706" alt="Screenshot 2024-05-20 at 12 53 13 PM" src="https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/127151429/9afedb8e-16db-4852-849e-c131e8ca1faa">

Let me know if anything was confusing or you want a better explanation of anything!

2024-05-21 21:33 UTC, benmartin-coforma commented
I think we'll also need to hit CPA-AD specifically; it has its own version of this question, just like MSC-AD

2024-05-22 14:26 UTC, keeysnc commented on services/ui-src/src/measures/2024/MSCAD/questions/DataSource.tsx
> +                  <p className="ds-c-alert__text">
I think you can use CUI.Text for this instead of p tag for consistency purposes.

2024-05-22 14:26 UTC, keeysnc commented on services/ui-src/src/shared/commonQuestions/DataSource.tsx
> +            <p className="ds-c-alert__text">
Same suggestion for the p tag

2024-05-22 14:26 UTC, keeysnc commented on services/ui-src/src/shared/commonQuestions/DataSourceCahps.tsx
> +                  <p className="ds-c-alert__text">
Same suggestion for the p tag

2024-05-24 14:37 UTC, ajaitasaini commented on services/ui-src/src/measures/2024/CPAAD/questions/DataSource.tsx
> +              (coreset === "adult" || coreset === "child") &&
that's a good point, and i guess this check is not doing anything. will remove!

2024-05-24 14:39 UTC, ajaitasaini commented on services/ui-src/src/shared/commonQuestions/DataSourceCahps.tsx
> +export const DataSourceRadio = ({
I believe I added this in case we would end up using DataSourceRadio for a 2024 or beyond measure, but I was not too sure about this myself. I can follow up with Aileen and if it looks unnecessary then I can scrap the changes for this file!

2024-05-24 14:45 UTC, ajaitasaini commented on services/ui-src/src/measures/2024/AABAD/index.tsx
> +          <CMQ.DataSource coreset="adult" />
1. yes we can match the `DateRange` pattern!
2. there is no existing prop from what I know, and other than the pattern `DateRange` follows, the only other similar example we noticed was passing in `healthHomeMeasure={true}` or `childMeasure={true}` for DefinitionOfPopulation. We originally were passing in a prop in a very similar pattern, and then moved to `coreset = "_____"`, etc so it was more reusable as a prop

2024-05-24 18:04 UTC, gmrabian commented on services/ui-src/src/measures/2024/AABAD/index.tsx
> +          <CMQ.DataSource coreset="adult" />
I agree pathname isn't great. I think 1. is the best option, matching it with the DateRange pattern. Or maintaining `coreset` if that's a pattern you are starting to use widely.

Thanks for hearing me out!

2024-05-29 14:29 UTC, karla-vm submitted a review, later dismissed

2024-05-29 14:41 UTC, gmrabian requested changes

2024-05-29 14:41 UTC, gmrabian commented on services/ui-src/src/measures/2024/WCCCH/index.tsx
> +          <CMQ.DataSource data={PMD.dataSourceData} type="adult" />
this is a child measure, no?

2024-05-29 14:41 UTC, gmrabian commented on services/ui-src/src/measures/2024/WCCCH/index.tsx
> +          <CMQ.DataSource data={PMD.dataSourceData} type="adult" />
looks like the DateRange value below is wrong as well

2024-05-29 14:53 UTC, gmrabian approved these changes

2024-05-29 16:10 UTC, karla-vm approved these changes
tested in deployed instance, looks good!

2024-05-29 16:11 UTC, merged