Add Measurement Specification Description Verbiage
Enterprise-CMCS/macpro-mdct-qmr pull request #2244
Opened 2024-05-21 13:34 UTC by keeysnc

### Description

### Related ticket(s)

CMDCT-

---
### How to test

### Notes

---
### Pre-review checklist

- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
- [ ] I have performed a self-review of my code
- [ ] I have manually tested this PR in the deployed cloud environment

---
### Pre-merge checklist

#### Review
- [ ] Design: This work has been reviewed and approved by design, if necessary
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

#### Security
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._

- [ ] These changes are significant enough to require an update to the SIA.
- [ ] These changes are significant enough to require a penetration test.
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2024-05-24 13:48 UTC, gmrabian submitted a review, later dismissed
Looks good! This shows up for past years as well, but I'm guessing that's ok

2024-05-29 13:42 UTC, ailZhou requested changes
So i double checked with David because @gmrabian made a good point. This is only for 2024 and onward, so it needs to follow the example that is in OMS. Add the text into the labels/2024/commonQuestionsLabel.tsx and then render it based on whether that key exist in the object.

<img width="619" alt="Screenshot 2024-05-29 at 9 40 16 AM" src="https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/127151429/d8341c29-3216-4761-a911-d836228c02d9">

2024-06-03 20:08 UTC, gmrabian approved these changes

2024-06-03 20:12 UTC, ailZhou commented on services/ui-src/src/shared/commonQuestions/MeasurementSpecification.tsx
> +  const measureSpecLabels: any = useContext(SharedContext);
I think this is a double call as there's already a `useContext(SharedContext);` call in line 107?

2024-06-03 20:21 UTC, ailZhou approved these changes

2024-06-04 14:58 UTC, gmrabian approved these changes

2024-06-04 14:59 UTC, merged