CPU-AD Update Performance Measure Text Formatting
Enterprise-CMCS/macpro-mdct-qmr pull request #2245
Opened 2024-05-21 15:40 UTC by keeysnc

### Description
Updated Performance Measure question text for CPU-AD measure

Previous
<img width="738" alt="Screenshot 2024-05-21 at 11 38 26 AM" src="https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/14514294/6eeef856-b858-4be9-b478-545172f68cf8">

Updated Screenshot:
<img width="991" alt="Screenshot 2024-05-21 at 11 22 51 AM" src="https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/14514294/f9f4974f-04fb-4d6a-ab93-ee7862ecec2b">

### Related ticket(s)

CMDCT- https://jiraent.cms.gov/browse/CMDCT-3622

---
### How to test
1. Go to CPU-AD measure 
2. Select Measurement Specification
3. Scroll down to see Performance Measure section. (Text should be updated to look like screenshot)

### Notes

---
### Pre-review checklist

- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
- [ ] I have performed a self-review of my code
- [ ] I have manually tested this PR in the deployed cloud environment

---
### Pre-merge checklist

#### Review
- [ ] Design: This work has been reviewed and approved by design, if necessary
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

#### Security
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._

- [ ] These changes are significant enough to require an update to the SIA.
- [ ] These changes are significant enough to require a penetration test.
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2024-05-22 13:30 UTC, ailZhou requested changes

2024-05-22 13:30 UTC, ailZhou commented on services/ui-src/src/measures/2024/shared/CommonQuestions/PerformanceMeasure/data.ts
> +  questionItem?: string;
I don't see this being called, is it still being used?

2024-05-22 13:30 UTC, ailZhou commented on services/ui-src/src/index.scss
> -li::marker {
So the bold is actually being used on the numbers in the qualifier section. 
![Screenshot 2024-05-22 at 9 15 28 AM](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/127151429/d33c25b0-22e4-4ac7-b93f-e52d494faa63)

Maybe add it back as a class selector to  `{yeay}/shared/Qualifiers/index.tsx ` file? This is where the list call is:
<img width="572" alt="Screenshot 2024-05-22 at 9 28 09 AM" src="https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/127151429/85fb59ad-11b6-4c2c-8426-274644b52d67">

2024-05-22 17:46 UTC, ailZhou approved these changes
lgtm! tested in browser, thank you for making the css change!

2024-05-23 20:34 UTC, ajaitasaini approved these changes

2024-05-23 20:35 UTC, merged