CMDCT-3689: adding new definition of denominator options for various coresets
Enterprise-CMCS/macpro-mdct-qmr pull request #2279
Opened 2024-06-10 20:16 UTC by angelaco11

### Description
According to [this](https://jiraent.cms.gov/browse/CMDCT-3689) ticket, the definition of denominator needed to be changed for various core sets. I updated these components to still use one component but conditionally render options based on which core set it is. I included screenshots of all the different types below:

Adult medicaid:
![Screenshot 2024-06-10 at 4 09 06 PM](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/16945230/f8e04fc1-f773-47b0-a7b3-d39ac96a618d)

Adult CHIP: 
![Screenshot 2024-06-10 at 4 09 27 PM](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/16945230/5ad6f36f-bfc1-491b-9052-456aeb024af6)

Child 
![Screenshot 2024-06-10 at 4 09 45 PM](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/16945230/1abceb13-672f-4251-bb77-04d2da4648e5)
medicaid:

Child CHIP:
![Screenshot 2024-06-10 at 4 10 04 PM](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/16945230/e6c36b0d-f7db-4d50-ad95-ce82ab1b4dd8)

Adult not separate:
![Screenshot 2024-06-10 at 4 07 09 PM](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/16945230/0e45d118-05e1-4647-88af-99dd04ce11f9)

Child not separate:
![Screenshot 2024-06-10 at 4 07 31 PM](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/16945230/e1b47df4-08cc-4de1-9a21-9c7a54617955)

Health home:
![Screenshot 2024-06-10 at 4 07 54 PM](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/assets/16945230/ac95bb30-7139-4c29-8c5f-7e4ff19bed2e)

---
### How to test
To test:
1. Navigate to each of the different core sets: Adult medicaid, Adult CHIP, Child Medicaid, Child CHIP, Adult not separate, Child not separate, Health home (you can find the last 3 with `stateUserDC` user)
2. Select a measure and scroll down to Definition of Population and make sure that all the stuff under Definition of denominator matches the appropriate new definitions in the description of [this](https://jiraent.cms.gov/browse/CMDCT-3689) ticket

---
### Pre-review checklist

- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
- [ ] I have performed a self-review of my code
- [ ] I have manually tested this PR in the deployed cloud environment

---
### Pre-merge checklist

#### Review
- [ ] Design: This work has been reviewed and approved by design, if necessary
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

#### Security
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._

- [ ] These changes are significant enough to require an update to the SIA.
- [ ] These changes are significant enough to require a penetration test.
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2024-06-10 20:18 UTC, angelaco11 commented on services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx
> +        value: DC.DENOMINATOR_INC_MEDICAID_POP,
Not sure about these values. What are they used for? Do child measures need have different values than standard measures? would love any amount of context you all have here

2024-06-11 16:31 UTC, angelaco11 commented on services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx
> +        ${coreSetOptions[coreSetType].description}
I know this seems kind of weird to have partial sentences stored as constants for each core set. But this seemed the cleanest to me instead of doing aggressive amounts of conditional string rendering inside this Text element (they're different for 3 core sets, medicaid, CHIP and health home). I also didn't want to store the whole description (starting with `For example`) in the coreSetOptions descriptions since it was redundant and would clutter that object even more. 

Do you guys have any opinions here? I'm open to any suggestions

2024-06-11 16:54 UTC, angelaco11 commented on services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx
> +      "Medicaid (Title XIX) beneficiaries, Medicaid-Expansion CHIP (Title XXI) beneficiaries,",
see [this](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/2279/files#r1635177499) comment for the reasoning behind these partial descriptions

2024-06-12 13:12 UTC, ailZhou requested changes
At a quick glance, the changes are appearing locally for me and it looks to be matching the ask. i also appreciate the organization you've added to this file, its definitely way more readable of what the options labels are for each coreSet 🎉 

unfortunately i need to ask for a change. so the "fun" thing about QMR updates, all changes are only meant for the current year and forward, previous years structure has to be preserved like its in a museum. This component is shared for 2021 - 2023 reports as well, so we need keep those labels along with these new labels in this file somehow. Or if you think its different enough and a new file should be made?

2024-06-13 16:05 UTC, angelaco11 commented on services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx
> +  const yearIs2024 = location.pathname.includes("/2024");
let me know if there's a better way to detect the year in these shared components. I know the parent components that renders DefintionOfPopulation has the year, but then I would have to pass it through as a prop approximately 10,000 times lol

2024-06-14 16:33 UTC, angelaco11 commented
> At a quick glance, the changes are appearing locally for me and it looks to be matching the ask. i also appreciate the organization you've added to this file, its definitely way more readable of what the options labels are for each coreSet 🎉
> 
> unfortunately i need to ask for a change. so the "fun" thing about QMR updates, all changes are only meant for the current year and forward, previous years structure has to be preserved like its in a museum. This component is shared for 2021 - 2023 reports as well, so we need keep those labels along with these new labels in this file somehow. Or if you think its different enough and a new file should be made?

This is a great callout, thank you Aileen! I have officially updated my PR to address this change request

2024-06-14 19:31 UTC, ailZhou submitted a review, later dismissed

2024-06-14 20:06 UTC, rocio-desantiago commented on services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx
> +  [id: string]: {
is this `id` the same as `coreSetId`?

2024-06-14 20:16 UTC, rocio-desantiago submitted a review, later dismissed
Thank you for the context Angela 👍

2024-06-17 13:32 UTC, angelaco11 commented on services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx
> +  [id: string]: {
I updated these names to be more specific! They're slightly different so I named each one accordingly

2024-06-17 16:29 UTC, benmartin-coforma submitted a review, later dismissed

2024-06-17 16:31 UTC, benmartin-coforma commented on services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx.rej
We'd better leave this file out; I think it was auto-generated by `git apply`

2024-06-17 16:36 UTC, angelaco11 commented on services/ui-src/src/shared/commonQuestions/DefinitionsOfPopulation.tsx.rej
ooh good catch!!!

2024-06-17 23:36 UTC, benmartin-coforma approved these changes
I am a fan of the code here, and I'd like to get this merged in sooner than later. The fact that it hasn't deployed to an ephemeral environment means that I can't run any tests there to give myself warm fuzzy feelings.

Maybe the actions are misbehaving because of the fork? Or some other one-off weirdness? This may be a case where it makes sense to merge into master first, in order to run our deployed-env tests. Especially given I don't see how anything in this PR could behave differently deployed vs locally.

2024-06-18 12:40 UTC, BearHanded approved these changes

2024-06-18 12:40 UTC, merged