added placeholder text
Enterprise-CMCS/macpro-mdct-qmr pull request #2371
Opened 2024-08-15 18:47 UTC by ajaitasaini

### Description

### Related ticket(s)

CMDCT-

---
### How to test

### Notes

---
### Pre-review checklist

- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
- [ ] I have performed a self-review of my code
- [ ] I have manually tested this PR in the deployed cloud environment

---
### Pre-merge checklist

#### Review
- [ ] Design: This work has been reviewed and approved by design, if necessary
- [ ] Product: This work has been reviewed and approved by product owner, if necessary

#### Security
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._

- [ ] These changes are significant enough to require an update to the SIA.
- [ ] These changes are significant enough to require a penetration test.
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2024-08-16 16:24 UTC, rocio-desantiago requested changes
I think it's just missing the title in bold: 
**About the Combined Medicaid and CHIP Rate**

2024-08-16 16:29 UTC, rocio-desantiago approved these changes
Scratch that. I just realized that's supposed to represent the existing title at the top lol. This looks good 👍

2024-08-16 16:47 UTC, rocio-desantiago commented
Confirmed the text appears

<img width="600" alt="combined-rates-language" src="https://github.com/user-attachments/assets/42352f3a-1b35-4666-b70a-34b054c4b9d4">

2024-08-19 17:15 UTC, angelaco11 approved these changes

2024-08-19 20:58 UTC, merged